services:
  service:
    image: registry.gitlab.com/gogogo2712128/bc-backend/member_service:latest
    environment:
      - jwtSecretkey=${jwtSecretkey}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GAME_SERVER=${GAME_SERVER}
      - WALLET_SERVER=${WALLET_SERVER}
      - SMTP_URL=${SMTP_URL}
      - Environment=${Environment}
      - Port=${Port}
      - MYSQL_URL
    ports:
      - ${APP_PORT}:8080
    networks:
      - bc-network
    restart: always
networks:
  bc-network:
    external: true